channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-apeglm=1.16.0
  - bioconductor-deseq2=1.34.0
  - bioconductor-genomeinfodbdata=1.2.7
  - bioconductor-glmgampoi=1.6.0
  - bioconductor-scran=1.22.1
  - bioconductor-scuttle=1.4.0
  - boto3=1.34.152
  - fsspec=2024.6.1
  - joblib=1.4.2
  - loguru=0.7.2
  - matplotlib=3.9.1
  - pandas=2.2.2
  - polars=1.2.1
  - poppler=22.12.0
  - pyarrow=10.0.1
  - r-arrow=10.0.1
  - r-devtools=2.4.5
  - r-dofuture=1.0.0
  - r-domc=1.3.8
  - r-dplyr=1.1.2
  - r-future=1.32.0
  - r-ggbeeswarm=0.7.2
  - r-ggplot2=3.4.2
  - r-gridextra=2.3
  - r-hmisc=5.1_0
  - r-knitr=1.43
  - r-logger=0.2.2
  - r-magick=2.7.4
  - r-multidplyr=0.1.3
  - r-progress=1.2.2
  - r-progressr=0.13.0
  - r-rcpp=1.0.10
  - r-rcppalgos=2.7.2
  - r-rmarkdown=2.22
  - r-testthat=3.1.8
  - r-tidyr=1.3.0
  - s3fs=0.4.2
  - scikit-learn=1.5.1
  - seaborn=0.13.2
  - statsmodels=0.14.2
  - tqdm=4.66.4
  - xgboost=2.1.1
  - xlsxwriter=3.1.9
